name: Deployment Notifications

on:
  workflow_call:

permissions:
  contents: read

jobs:
  notification:
    runs-on: ubuntu-latest
    environment: utilCICD

    steps:
      - name: Deployment Notification
        run: |
          echo "Deployment workflow completed."
          echo "Repository: ${{ github.repository }}"
          echo "Commit: ${{ github.sha }}"
          echo "Triggered by: ${{ github.actor }}"